### ISSUE TITLE
Minotore walk animation not working

### ISSUE THREAD

**Issue by Zefz** [egoboo/egoboo#121]
Minotores do not move their feet when walking, instead floating around. Their attack animation seems to work well though...

Observed in Imprisoned One II.

**Comment by penguinflyer5234** [comment]
Minotores only have a sneaking animation (WA), they do not have a walking or running animation (WB and WC).

**Comment by Zefz** [comment]
I've observed the same issue with the Rogue and some Cobols though. If objects are walking slowly, they seem to be doing the ACTION_DA (idle/dance) animation instead of a walk animation. I think I might have messed up some threshold after adding the new Stealth system.

**Comment by Zefz** [comment]
Fixed by #150.
