### ISSUE TITLE
Character outside of level bounds

### ISSUE THREAD

**Issue by michaelheilmann** [egoboo/egoboo#17]
The player character can walk outside of level bounds.
Investigate if this an engine or a level issue.

![unbenannt](https://cloud.githubusercontent.com/assets/3015294/5604341/fbde160c-93b6-11e4-800a-dc32486da24e.png)

**Comment by penguinflyer5234** [comment]
Far edge mode is set to TRUE in wawalite.txt, so it's an engine bug. Egoboo should be stopping you 1-2 tiles before the edge.

**Comment by penguinflyer5234** [comment]
This is actually a level bug, cartman adds the impassable flags for the edges while EgoMap does not.

**Comment by Zefz** [comment]
But the game should return for everything outside the level bounds as Impassable, so I'm not sure why this still happens.

**Comment by Zefz** [comment]
This seems to be fixed now. You can no longer move outside the level. Movement is still weird when touching the edges but at least it's non-critical.
