### ISSUE TITLE
Black characters

### ISSUE THREAD

**Issue by michaelheilmann** [egoboo/egoboo#194]
Characters are illuminated with solid black, the issue goes away over time.
Observed in
- 6cc2caadc9d0ba8c81c2d4ae44fe711bdaf5acc6
- 77c31f56acaddd21891ebec4c038ff2b7946df45

Not observed in
- 34885f15b28fc4c853ed70737d817067258872f9 
- 85349aa3ca5b070d68cacbfc3f2ccf93bc714ead 
- f2f1a8d8f98fe3f42d23da01cd37c0c57ab88e90 
- 8e4f400712664511f239a24283281f5e2b09e82b 
- dbff370dec9f9660f4bdafdc7a35d40c040245ae 
- 22968fe0dbaacbb6077c515f769af51313e999fd 

Reproduce:
Wizard Starter, click the start module button immediatly when it appears.

The offending commit is 77c31f56acaddd21891ebec4c038ff2b7946df45 as its preceeding commit 34885f15b28fc4c853ed70737d817067258872f9 is working.

Most likely, the reason for the bug is
```
    self.vrt_lst = new GLvertex[vlst_size];
```
which replaces
```
    self.vrt_lst = EGOBOO_NEW_ARY(GLvertex, vlst_size);

```
. However, the operator `new []` version is not initializing the `GLvertex` array elements, the `EGOBOO_NEW_ARY` version does.

**Comment by Zefz** [comment]
85349aa works fine.
