### ISSUE TITLE
Cannot run without SDL force-feedback joystick support.

### ISSUE THREAD

**Issue by tlhonmey** [egoboo/egoboo#271]
If your libSDL is compiled without haptic/force-feedback support, egoboo complains about this and refuses to start.

Give that joysticks, let alone force-feedback ones, are not required to play the game, use of force-feedback should be made optional.

**Comment by michaelheilmann** [comment]
@tlhonmey Thank you. I will commit a fix that will hopefully resolve this issue. However, as I can not test it (I assume you are running Linux or Mac), there might be subsequent issues. In any case, Egoboo will not terminate anymore simply because libSDL was not compiled with haptic support.

**Comment by tlhonmey** [comment]
It will take me a little while to test this since, after pulling the latest code, it seems the project now requires gcc 5 (for the c++14 standard).  So I've got to update a bunch of stuff.

**Comment by Zefz** [comment]
@tlhonmey GCC 4.9.2 should be sufficient to compile Egoboo (Travis CI use this version to compile the game).

**Comment by tlhonmey** [comment]
Now compiles and runs without haptic support.
