### ISSUE TITLE
Some items return to home when dropped.

### ISSUE THREAD

**Issue by tlhonmey** [egoboo/egoboo#285]
Especially items dropped by fallen foes or looted from chests.  Pick it up, carry it across the dungeon, drop it, and it goes back to its starting place.  This can cause trouble with the puzzles in certain maps.

**Comment by tlhonmey** [comment]
Seems to happen most consistently when items land on top of a corpse, but have also seen it with items on moving platforms or tables or bookshelves.

**Comment by Zefz** [comment]
Sounds like a physics logic bug related to platforms.

**Comment by Zefz** [comment]
Fixed by #295
