### ISSUE TITLE
When restarting the same module, the screen stays dark for a short while but the character can already move

### ISSUE THREAD

**Issue by michaelheilmann** [egoboo/egoboo#31]
When restarting the same module, the screen stays dark for a short while (4-5s) but the character
can already move. 

Steps to reproduce this bugs:
- Start the soldier module
- Restart the module and walk forward while the screen is still dark

**Comment by penguinflyer5234** [comment]
Restarting over and over adds more time before the lighting updates.
Also, starting a new module instead of restarting does the same thing.

**Comment by Zefz** [comment]
Is this related to my Camera update #26? Or did this bug happen before porting the camera system?

**Comment by michaelheilmann** [comment]
@Zefz It might be have been in before as lighting was effectively turned off. However, as penguinflyer5234 already identified the cause, I suppose he will have a fix soon.

**Comment by penguinflyer5234** [comment]
I have a fix, but it only works MAX_PLAYER times before running out of renderlists.
