### ISSUE TITLE
Crash on starting Wizard Starter

### ISSUE THREAD

**Issue by Zefz** [egoboo/egoboo#311]
On latest master I get the following issue when starting the Wizard Starter:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  invalid IDSZ
Aborted
```

After a little debugging I found that the issue originates from the game trying to load a weather effect particle (when none exits for the Wizard Starter). It tries to load a non-existing `weather_effect_none.txt` particle file or something like that.

**Comment by michaelheilmann** [comment]
On it; invalid IDSZ is usually raised if an IDSZ is somewhat malformed i.e. is not of the form `'['x^4']'` where `x = ('a'..'z')|('A'..'Z')|('0'..'9')`. In fact, the new scanner is more strict, so maybe we have missed some weird special case (or it was a bug anyway but went unnoticed).
