### ISSUE TITLE
25 fps limit (frame rate is too low)

### ISSUE THREAD

**Issue by qubodup** [egoboo/egoboo#332]
It appears that egoboo will not go beyond 25fps by default. How to increase this to 60fps?

**Comment by Zefz** [comment]
@qubodup 

Are you using the old 2.8.1 release or the new nightly version? 
https://github.com/egoboo/egoboo/releases/download/Egoboo-Nightly/binaries-Release-x64.zip (64-bit)
https://github.com/egoboo/egoboo-assets/archive/master.zip (data files)

The new version should have 60 FPS by default.
