### ISSUE TITLE
Improve billboards

### ISSUE THREAD

**Issue by Zefz** [egoboo/egoboo#35]
Billboards (these floating text above characters). I don't like them, they ruin immersion and are kinda buggy. They might be useful for specific things, but having text floating above each chair, bookcase and monster is kinda irritating.

Luckly there is an in-game option to disable these, but they are still buggy.

**Comment by penguinflyer5234** [comment]
I was under the impression that the character name billboards were for debugging purposes.

**Comment by Zefz** [comment]
What about the damage indicators? (immune! badly injured, etc.)

Those might be better replaced by numbers (zelda-like damage count floaters) to show how effective your attacks are.

**Comment by Zefz** [comment]
I like the new font a lot better. I still want to make large amounts of damage be drawn in bigger font and small amounts in small font. Is this possible using the current Font system? @penguinflyer5234

**Comment by Zefz** [comment]
Fixed in #218.
