### ISSUE TITLE
Can't compile on debian stretch stable amd64

### ISSUE THREAD

**Issue by ghost** [egoboo/egoboo#354]
This is my last attempt to compile egoboo on stretch before I jump to testing again. The "make" step gives the following error : 

> src/egolib/fileutil.c: In member function ‘void ReadContext::readOldString0()’:
src/egolib/fileutil.c:1244:27: error: ‘ordered_choice’ is not a member of ‘id::parsing_expressions’
     static const auto p = id::parsing_expressions::ordered_choice(WHITE_SPACE(), NEW_LINE(), END_OF_INPUT());
                           ^~

**Comment by michaelheilmann** [comment]
How did you acquire the source code? By using Git or by downloading a zip file?
What compiler are you using?

**Comment by libregametester** [comment]
I cloned the git, and the compiler must have been the default debian
stretch compiler, which is gcc 6.3 at the moment.

--

**Comment by michaelheilmann** [comment]
Check if the file exists at all (on disk) and what it contains.
Idlib is in the folder _idlib_ and is a submodule.
