### ISSUE TITLE
Particle shenanigans

### ISSUE THREAD

**Issue by penguinflyer5234** [egoboo/egoboo#5]
Some particles have broken physics:
Falling blud from Lumpkins doesn't hit the ground
Money can't be picked up
Weapon particles are misaligned

**Comment by Zefz** [comment]
Dead bodies in water seem to constantly spawn ripples.

**Comment by Zefz** [comment]
Money can be picked up and weapon particles are no longer misaligned.

**Comment by Zefz** [comment]
I think all these are fixed in latest commit.

Another particle issue remains though:
Attack Particles of Ghouls when they are close to you (seem to despawn before they can hurt you)

**Comment by Zefz** [comment]
The particle hit issue is filed in #70
