### ISSUE TITLE
Fairy Light does not disappear

### ISSUE THREAD

**Issue by michaelheilmann** [egoboo/egoboo#86]
When the fairy light spell is dispelled, the fairy light selects a random direction and when hitting an obstacle (wall) it disappears. The fairy light still disappears in commit https://github.com/egoboo/egoboo/commit/2b97cd0e9ab3883fa88409dc734dd91c06430461 when it hits a well. Since commit https://github.com/egoboo/egoboo/commit/aa82523725321719542487c1649b14e9a6c166cb it doesn't disappear anymore simply stopping at the obstacle it hit.

Correct behavior is: The light should disapear with a poof effect.

**Comment by penguinflyer5234** [comment]
Disabling lines 2769-2772 in game/entities/Particle.cpp fixes this issue, but I'm unsure if this is the "correct" behavior.
(the lines should start with `// clear out the attachment if the character doesn't exist at all`)
